HARD_FAIL = [
    "LEAKAGE_SUSPECTED",
    "PBO_TOO_HIGH",
    "DD_LIMIT_BREACH",
    "CPCV_WORST_TOO_LOW",
]

SOFT_WARN = [
    "TURNOVER_TOO_HIGH",
    "CALIBRATION_BAD",
    "REGIME_DEPENDENT",
    "LABEL_IMBALANCE",
]
